include config.mk

include fst.mk
include tgl.mk
include sound.mk
include object.mk

all: $(ALL_TARGETS)

.PHONY : clean

output_clean_targets:
	echo $(ALL_CLEAN_TARGETS)

clean: output_clean_targets $(ALL_CLEAN_TARGETS)

